import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PrelineScript from '@/components/PrelineScript'
import ToastProvider from '@/components/Providers/ToastProvider'
import AuthProvider from '@/components/Providers/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <PrelineScript />

      <body className={inter.className}>
        <ToastProvider />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
